### ISSUE TITLE
repositories with no description cause an error

### ISSUE THREAD

**Issue by zkoppert** [zkoppert/innersource-crawler#50]
Repositories that don't have a description cause the following error:

```bash
Traceback (most recent call last):
  File "/action/workspace/crawler.py", line 84, in <module>
    innersource_repo["score"] = repo_activity.score.calculate(
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.[11](https://github.com/innersource-portal-demo/project-portal-for-innersource/actions/runs/6279610170/job/17055587875#step:4:12)/site-packages/repo_activity/score.py", line 54, in calculate
    len(repo["description"]) > 30
    ^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: object of type 'NoneType' has no len()
```

A workaround is to add a description but it would be better if the crawler could handle repositories without descriptions gracefully and continue running.

**Comment by issamansur** [comment]
Can I help with this?

**Comment by zkoppert** [comment]
Yeah that would be great!
